//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Reservas.Entidades;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class CarrosConsultaDisponiveisPage : WesPage
{
    
    protected void Page_Load(object sender, System.EventArgs e)
    {
        Modelo.Initialize("MODELOSCARROS", new List<string>() { "NOME" });
        GridCarrosWes.UserDefinedCriteriaWhereClause = "1 = 2";
    }

    protected void Busca_Click(object sender, EventArgs e)
    {
        DateTime dia = DateTime.MinValue;
        DateTime.TryParse(Dia.Text, out dia);

        if (Modelo.SelectedItems != null
            && Modelo.SelectedItems.Length > 0 && dia != DateTime.MinValue)
        {
            Handle modelo = Modelo.SelectedItems[0].id;

            var carrosDao = CarrosDao.CreateInstance();

            var carrosDiaSelecionado = carrosDao.CarrosDisponiveisPorModeloEPeriodo(modelo, dia, dia);

            List<int> handles = new List<int>();
            foreach (var carro in carrosDiaSelecionado)
            {
                handles.Add(carro["HANDLE"].GetInt32());
            }

            GridCarrosWes.UserDefinedCriteriaWhereClause = handles.Count > 0 ? string.Format("A.HANDLE IN ({0})", string.Join(", ", handles)) : "1 = 2";
            GridCarrosWes.ForceUpdate();

            GridCarrosAsp.DataSource = carrosDiaSelecionado;
            GridCarrosAsp.ApplyMetronicStyle();
            GridCarrosAsp.DataBind();
        }
        else
        {
            GridCarrosAsp.DataSource = null;
            GridCarrosAsp.DataBind();
        }
    }
}
