//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Reservas.Entradas;
using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;



public partial class ReservasWizardNovaReservaPage : WesPage
{
    public VtWizardReserva VtReserva
    {
        get
        {
            return RESERVA.GetEntity() as VtWizardReserva;
        }
    }

    public VtWizardPessoa VtPessoa
    {
        get
        {
            return PESSOA.GetEntity() as VtWizardPessoa;
        }
    }
    
    protected void Page_Load(object sender, System.EventArgs e)
    {
        PESSOA.CommandExecuted += PESSOA_CommandExecuted;
        RESERVA.CommandExecuted += RESERVA_CommandExecuted;
    }

    private void RESERVA_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        throw new NotImplementedException();
    }

    private void PESSOA_CommandExecuted(object sender, FormCommandExecuteArgs e)
    {
        throw new NotImplementedException();
    }
}
