//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Common;
using Benner.Tecnologia.Common.Components;
using Benner.Tecnologia.Wes.Components;
using Benner.Tecnologia.Wes.Components.WebApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class SemBEFPaisesSBPage : WesPage
{
    private EntityDefinition paisDefinition = EntityDefinition.GetByName("PAISES");
    protected override void OnInit(EventArgs e)
    {
        base.OnInit(e);
        btnSalva.Click += BtnSalva_Click;
    }

    private void BtnSalva_Click(object sender, EventArgs e)
    {
        EntityBase pais = Entity.Create(paisDefinition);
        pais.Fields["NOME"] = txtPais.Text;
        pais.Save();
        PintaGrid();
    }

    protected void Page_Load(object sender, System.EventArgs e)
    {
        if (!Page.IsPostBack)
        {
            PintaGrid();
        }
    }

    private void PintaGrid()
    {
        var pais = Entity.GetAll(paisDefinition);
        gridPaises.DataSource = pais;
        gridPaises.DataBind();
        gridPaises.ApplyMetronicStyle();
    }
}
